spring.application.name=Spring_Security

spring.main.banner-mode=off
logging.level.org.springframework=ERROR

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_db
spring.datasource.username=postgres
spring.datasource.password=Omega3@5567

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.org.springframework.boot.autoconfigure.security=INFO

